config_version: 1.0
training:
  trainer: mmf
  seed: 52482122
  experiment_name: run
  max_updates: 22000
  max_epochs: null
  log_interval: 100
  logger_level: info
  log_format: simple
  log_detailed_config: false
  should_not_log: false
  colored_logs: true
  tensorboard: false
  cudnn_benchmark: false
  wandb:
    enabled: false
    entity: null
    project: mmf
    name: run
    log_checkpoint: false
  batch_size: 64
  batch_size_per_device: null
  update_frequency: 1
  num_workers: 0
  fast_read: false
  dataset_size_proportional_sampling: true
  pin_memory: false
  persistent_workers: true
  checkpoint_interval: 1000
  evaluation_interval: 1000
  clip_gradients: false
  clip_norm_mode: all
  early_stop:
    enabled: false
    patience: 4000
    criteria: hateful_memes/roc_auc
    minimize: false
  lr_scheduler: true
  lr_steps: []
  lr_ratio: 0.1
  use_warmup: false
  warmup_factor: 0.2
  warmup_iterations: 1000
  device: cpu
  local_rank: null
  verbose_dump: false
  find_unused_parameters: true
  evaluate_metrics: false
  detect_anomaly: false
  fp16: false
  callbacks: []
  exit_on_nan_losses: true
trainer:
  type: lightning
  params:
    gpus: 1
    num_nodes: 1
    precision: 32
    deterministic: false
    benchmark: false
    max_steps: 22000
    max_epochs: null
    gradient_clip_val: 0.0
    num_sanity_val_steps: 0
    enable_checkpointing: true
    accumulate_grad_batches: 1
    val_check_interval: 1000
    log_every_n_steps: 100
    logger: false
    limit_val_batches: 1.0
    enable_progress_bar: false
    resume_from_checkpoint: null
evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc
  use_cpu: false
  predict: false
  predict_file_format: csv
  reporter:
    type: file
    params: {}
model_config:
  concat_vl:
    num_classes: 2
    dropout: 0.1
    image_encoder:
      type: resnet152
      params:
        pretrained: true
        pool_type: avg
        num_output_features: 1
    text_encoder:
      params:
        module: linear
        in_dim: 300
        out_dim: 300
    fusion:
      params:
        in_features: 2348
        out_features: 512
    losses:
    - cross_entropy
    classifier:
      type: mlp
      params:
        in_dim: 512
        out_dim: 2
        num_layers: 0
    model: concat_vl
dataset_config:
  hateful_memes:
    data_dir: /Users/xys/Desktop/cs/DDA4220_Hateful_Memes/data
    depth_first: false
    fast_read: false
    use_images: true
    use_features: false
    images:
      train:
      - hateful_memes/defaults/images/
      val:
      - hateful_memes/defaults/images/
      test:
      - hateful_memes/defaults/images/
    features:
      train:
      - hateful_memes/defaults/features/detectron.lmdb
      val:
      - hateful_memes/defaults/features/detectron.lmdb
      test:
      - hateful_memes/defaults/features/detectron.lmdb
    annotations:
      train:
      - hateful_memes/defaults/annotations/train.jsonl
      val:
      - hateful_memes/defaults/annotations/dev_unseen.jsonl
      test:
      - hateful_memes/defaults/annotations/test_unseen.jsonl
    max_features: 100
    processors:
      text_processor:
        type: fasttext_sentence_vector
        params:
          max_length: null
          vocab:
            type: intersected
            embedding_name: glove.6B.300d
            vocab_file: hateful_memes/defaults/extras/vocabs/vocabulary_100k.txt
          preprocessor:
            type: simple_sentence
            params: {}
          model_file: wiki.en.bin
      bbox_processor:
        type: bbox
        params:
          max_length: 50
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
          - type: Resize
            params:
              size:
              - 256
              - 256
          - type: CenterCrop
            params:
              size:
              - 224
              - 224
          - ToTensor
          - GrayScaleTo3Channels
          - type: Normalize
            params:
              mean:
              - 0.46777044
              - 0.44531429
              - 0.40661017
              std:
              - 0.12221994
              - 0.12145835
              - 0.14380469
    return_features_info: false
datasets: hateful_memes
model: concat_vl
config: configs/experiments/defaults.yaml
run_type: train_inference
optimizer:
  allow_unused_parameters: false
  enable_state_sharding: false
  type: adam_w
  params:
    lr: 5.0e-05
    eps: 1.0e-08
scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 2000
    num_training_steps: 22000
env:
  cache_dir: /Users/xys/.cache/torch/mmf
  dataset_zoo: configs/zoo/datasets.yaml
  model_zoo: configs/zoo/models.yaml
  data_dir: /Users/xys/Desktop/cs/DDA4220_Hateful_Memes/data
  save_dir: ./save
  log_dir: ''
  report_dir: ''
  tensorboard_logdir: ''
  wandb_logdir: ''
  user_dir: /Users/xys/Desktop/cs/DDA4220_Hateful_Memes
distributed:
  init_method: null
  rank: 0
  port: -1
  backend: nccl
  world_size: 1
  no_spawn: false
checkpoint:
  resume: false
  resume_file: null
  resume_best: false
  resume_pretrained: false
  resume_zoo: null
  zoo_config_override: false
  pretrained_state_mapping: {}
  max_to_keep: -1
  save_git_details: true
  reset:
    all: false
    optimizer: false
    counts: false
    fp16_scaler: false
multitasking:
  enabled: true
  type: size_proportional
  params: {}
start_rank: 0
device_id: 0
